config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    resources :manager

    root 'dashboard#index'

    resources :pages do
      collection do
        post :rebuild
        get '/all' => 'pages#all'
        get '/find/:id' => 'pages#find'
      end
    end

    resources :products
    get '/products/find/:id' => 'products#find'
    post '/products/:product_id/property/:property_id/value/:value_id' => 'products#set_property_value'
    resources :categories do
      collection do
        post :rebuild
      end
    end

    resources :properties do
      post :values
      delete '/values/:id' => 'properties#delete_value'
    end

    resources :feedbacks

    get '/categories/find/:id' => 'categories#find'

    get '/product/photos/:product_id' => 'photos#find'
    post '/product/photos/upload' => 'photos#upload'

    get '/category/photos/:category_id' => 'photos#find_category'
    post '/category/photos/upload' => 'photos#upload_category'

    get '/gallery/photos/:gallery_id' => 'photos#find_gallery'
    post '/gallery/photos/upload' => 'photos#upload_gallery'

    delete '/photos/:id' => 'photos#destroy'
    put '/photos/edit/:id' => 'photos#update'

    resources :galleries do

    end

  end

  post '/feedback/create' => 'feedbacks#create'

  root 'pages#index'

  get '/pages/carousel/:id' => 'pages#carousel'

  get '/product/filters/' => 'products#filters'

  get '/catalog/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/*section/:category_id/product/:product_id' => 'pages#product'

  get '/catalog' => 'pages#catalog'
  get '/catalog/:id' => 'pages#category'
  get '/catalog/*section/:id' => 'pages#category'
  get '/catalog/*section/*section/:id' => 'pages#category'

  get ':id' => 'pages#show'

end

app/views/admin/pages/_form.slim
.panel.panel-success
  .panel-heading
    h3.panel-title Информация о странице

  .panel-body
    .alert.alert-danger ng-if="errors"
      h4.text-center При сохранении возникли следующие ошибки:
      br
      dl.dl-horizontal ng-if="errors.name" 
        dt Название: 
        dd ng-bind="errors.name[0]"
      dl.dl-horizontal ng-if="errors.path" 
        dt Путь: 
        dd ng-bind="errors.path[0]"
    .row
      .col-sm-9
        .form-group
          label for="name_ru" Название
          input.form-control#name_ru name="name" type="text" ng-model="obj.name" 

        .form-group
          label for="path" Путь(url, например - kamod, только латиницей)
          input.form-control#path type="text" ng-model="obj.path"

        .form-group.rich
          label for="body" Содержимое
          textarea.form-control#body name="obj.body" ng-model="obj.body" rows="10" 

      .col-sm-3
        .form-group
        .checkbox
          label
            input type="checkbox" ng-value="0" ng-model="obj.menu"
            | Показывать страницу в меню
        
        .form-group
          label for="parent_id" Привязать к категории каталога
          select.form-control#parent_id ng-model="category" ng-change="setCatalog(category)"
            -@categories.each do |i|   
              option value='{"name": "#{i.name}", "path": "#{i.full_path}"}'  
                = "#{'-' * i.level} #{i.name}"

        .form-group
          label for="parent_id" Родительская страница
          select.form-control#parent_id ng-model="obj.parent_id"
            -@pages.each do |i|
              option value="#{i.id}" 
                = "#{'-' * i.level} #{i.name}"

        .form-group
          .checkbox
            label
              input type="checkbox" value="true" ng-model="obj.feedback"
              | Привязать к странице форму обратной связи

app/views/admin/pages/edit.slim
form ng-init="obj.authenticity_token = '#{form_authenticity_token}'" ng-controller="PagesFormCtrl"

  .page-header
    h2 Добавить страницу
    .page-header-actions
      button.btn.btn-success type="submit" ng-click="update('#{@page.id}')" ng-init="findPage('#{@page.id}')"
        i.fa.fa-floppy-o
        | Сохранить
      =link_to "Отменить", admin_pages_path, :class => "btn btn-default"
      
  =render 'admin/pages/form'

app/views/admin/pages/index.slim
.page-header
  h2 Станицы сайта
  .page-header-actions
    = link_to new_admin_page_path, class: 'btn btn-success' do
      i class="fa fa-plus"
      ' Добавить страницу

.content.page
  ol.sortable_tree data-max_levels="5" data-rebuild_url="#{rebuild_admin_pages_url}"
    = sortable_tree @pages

app/views/admin/pages/new.slim
form ng-init="obj.authenticity_token = '#{form_authenticity_token}'" ng-controller="PagesFormCtrl"

  .page-header
    h2 Редактировать страницу
    .page-header-actions
      button.btn.btn-success type="submit" ng-click="submit()"
        i.fa.fa-floppy-o
        | Сохранить
      =link_to "Отменить", admin_pages_path, :class => "btn btn-default"

  =render 'admin/pages/form'

app/views/admin/pages/show.slim
h2.page-header=@page.name
div=@page.body