config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    resources :manager

    root 'dashboard#index'

    resources :pages do
      collection do
        post :rebuild
        get '/all' => 'pages#all'
        get '/find/:id' => 'pages#find'
      end
    end

    resources :products
    get '/products/find/:id' => 'products#find'
    post '/products/:product_id/property/:property_id/value/:value_id' => 'products#set_property_value'
    resources :categories do
      collection do
        post :rebuild
      end
    end

    resources :properties do
      post :values
      delete '/values/:id' => 'properties#delete_value'
    end

    resources :feedbacks

    get '/categories/find/:id' => 'categories#find'

    get '/product/photos/:product_id' => 'photos#find'
    post '/product/photos/upload' => 'photos#upload'

    get '/category/photos/:category_id' => 'photos#find_category'
    post '/category/photos/upload' => 'photos#upload_category'

    get '/gallery/photos/:gallery_id' => 'photos#find_gallery'
    post '/gallery/photos/upload' => 'photos#upload_gallery'

    delete '/photos/:id' => 'photos#destroy'
    put '/photos/edit/:id' => 'photos#update'

    resources :galleries do

    end

  end

  post '/feedback/create' => 'feedbacks#create'

  root 'pages#index'

  get '/pages/carousel/:id' => 'pages#carousel'

  get '/product/filters/' => 'products#filters'

  get '/catalog/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/*section/:category_id/product/:product_id' => 'pages#product'

  get '/catalog' => 'pages#catalog'
  get '/catalog/:id' => 'pages#category'
  get '/catalog/*section/:id' => 'pages#category'
  get '/catalog/*section/*section/:id' => 'pages#category'

  get ':id' => 'pages#show'

end

app/views/admin/sidebar/_sidebar.slim
.brand-cont
  a href="/admin/" class="logo" Rocket-cms

ul class="sidebar-nav"
  li=link_to "Станицы сайта", admin_pages_path
  li=link_to "Товары", admin_products_path
  li ng-class="{'active': menuActive == 'property'}"
    =link_to t('properties'), '#/properties'
  li=link_to "Категории товаров", admin_categories_path
  li ng-class="{'active': menuActive == 'galleries'}"
    =link_to "Фотографии", '#/galleries'
  li=link_to "Обратная связь", admin_feedbacks_path
  li=link_to "Администраторы", admin_manager_index_path

ul class="sidebar-nav users"
  -if current_manager
    li=link_to current_manager.email, admin_manager_path(current_manager) 
  li
    = link_to "Выйти", admin_signout_path, method: "delete"