config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    resources :manager

    root 'dashboard#index'

    resources :pages do
      collection do
        post :rebuild
        get '/all' => 'pages#all'
        get '/find/:id' => 'pages#find'
      end
    end

    resources :products
    get '/products/find/:id' => 'products#find'
    post '/products/:product_id/property/:property_id/value/:value_id' => 'products#set_property_value'
    resources :categories do
      collection do
        post :rebuild
      end
    end

    resources :properties do
      post :values
      delete '/values/:id' => 'properties#delete_value'
    end

    resources :feedbacks

    get '/categories/find/:id' => 'categories#find'

    get '/product/photos/:product_id' => 'photos#find'
    post '/product/photos/upload' => 'photos#upload'

    get '/category/photos/:category_id' => 'photos#find_category'
    post '/category/photos/upload' => 'photos#upload_category'

    get '/gallery/photos/:gallery_id' => 'photos#find_gallery'
    post '/gallery/photos/upload' => 'photos#upload_gallery'

    delete '/photos/:id' => 'photos#destroy'
    put '/photos/edit/:id' => 'photos#update'

    resources :galleries do

    end

  end

  post '/feedback/create' => 'feedbacks#create'

  root 'pages#index'

  get '/pages/carousel/:id' => 'pages#carousel'

  get '/product/filters/' => 'products#filters'

  get '/catalog/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/*section/:category_id/product/:product_id' => 'pages#product'

  get '/catalog' => 'pages#catalog'
  get '/catalog/:id' => 'pages#category'
  get '/catalog/*section/:id' => 'pages#category'
  get '/catalog/*section/*section/:id' => 'pages#category'

  get ':id' => 'pages#show'

end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_and_belongs_to_many :photos


  validates :name, length: {minimum: 1}
  validates :path, length: {minimum: 1}, uniqueness: true


  acts_as_nested_set
  include TheSortableTree::Scopes


  def full_path
    @parents = self.self_and_ancestors.select(:path)
    @path = @parents.map do |p|
      "/" + p.path
    end
    @path.join()
  end


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_and_belongs_to_many :photos
  
  acts_as_nested_set
  include TheSortableTree::Scopes

  def to_param
    "#{path}"
  end
  
  def full_path
    @parents = self.self_and_ancestors.select(:path)
    @path = @parents.map do |p|
      "/" + p.path
    end
    @path.join()
  end

  def front_full_path
    @parents = self.self_and_ancestors.select(:path)
    @path = ["/catalog"]
    @path += @parents.map do |p|
       "/" + p.path
    end
    @path.join()
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :signed_in_manager
  before_action :set_item, only: [:show, :find, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  include TheSortableTreeController::Rebuild


  def index
    @categories = Admin::Category.all.order('lft ASC')
    @clear_nill_category = Admin::Category.find_by_name("название")
    if @clear_nill_category
      @clear_nill_category.destroy
    end
  end

  def show
  end

  def new
    # @category = Admin::Category.new
    @category = Admin::Category.new(
        :path => "введите url", :name => "название"
    )
    @category.save validate: false
    @categories = Admin::Category.all
  end

  def edit
    @categories = Admin::Category.all
  end

  def find
    @category_translation = Admin::Category.find(params[:id])
    render :json => @category_translation
  end

  def update
    if @category.update(category_params)
      render :json => {success: @category}
    else
      render :json => {error: @category.errors}
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_item
    @category = Admin::Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:sortable, :parent_id, :path, :name)
  end
end

app/views/admin/categories/_form.slim
.panel.panel-info ng-controller="CategoriesFormCtrl"
  .panel-heading.clearfix
    h3.panel-title.pull-left Добавить новую категорию

  .panel-body
    form ng-init="obj.authenticity_token = '#{form_authenticity_token}'" 
      .alert.alert-danger ng-if="errors"
        h4.text-center При сохранении возникли следующие ошибки:
        br
        dl.dl-horizontal ng-if="errors.name" 
          dt Название: 
          dd ng-bind="errors.name[0]"
        dl.dl-horizontal ng-if="errors.path" 
          dt Путь: 
          dd ng-bind="errors.path[0]"
      .row
        .col-sm-6
          .form-group
            label for="name" Название
            input.form-control#name name="name" type="text" ng-model="obj.name" 

          .form-group
            label for="parent_id" Родительская категория
            select.form-control#parent_id ng-model="obj.parent_id"
              -@categories.each do |i|
                option value="#{i.id}" 
                  = "#{'-' * i.level} #{i.name}"

          .form-group
            label for="path" Путь(url, например - kamod, только латиницей)
            input.form-control#path type="text" ng-model="obj.path"

        .col-sm-6
          photos-uploaded resource-name="category" resource-id="#{@category.id}"
          uploader-component upload-url="/admin/category/photos/upload" resource-name="category_id" resource-id="#{@category.id}"


  .panel-footer
    -if @category.name.nil?
      button.btn.btn-success type="submit" ng-click="submit()" Добавить
    -else
      button.btn.btn-success type="submit" ng-click="update(#{@category.id})" ng-init="findCategory(#{@category.id})" Обновить
    | &nbsp;
    =link_to "Отменить", admin_categories_path, :class => "btn btn-default"

app/views/admin/categories/edit.slim
=render 'admin/categories/form'

app/views/admin/categories/index.slim
.page-header
  h2 Категории товара
  .page-header-actions
    = link_to new_admin_category_path, class: 'btn btn-success' do
      i class="fa fa-plus"
      ' Добавить категорию

.content
  ol.sortable_tree data-max_levels="5" data-rebuild_url="#{rebuild_admin_categories_url}"
    = sortable_tree @categories


/table class="table table-bordered"
  thead
    tr
      th id
      th Название
      th Путь
      th Действия

  /tbody
    -@categories.each do |item|
      tr
        td=item.id
        td=item.name
        td
          -item.self_and_ancestors.each do |i|
            = '/'
            = i.path
        td
          = link_to "Редактировать", edit_admin_category_path(item), class: 'btn btn-success'
          span &nbsp;
          = link_to "Удалить", admin_category_path(item), class: 'btn btn-danger', method: "delete"
            
            
            

app/views/admin/categories/new.slim
=render 'admin/categories/form'

app/views/admin/categories/show.slim
h2.page-header=@category.name
div=@category.path