config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    resources :manager

    root 'dashboard#index'

    resources :pages do
      collection do
        post :rebuild
        get '/all' => 'pages#all'
        get '/find/:id' => 'pages#find'
      end
    end

    resources :products
    get '/products/find/:id' => 'products#find'
    post '/products/:product_id/property/:property_id/value/:value_id' => 'products#set_property_value'
    resources :categories do
      collection do
        post :rebuild
      end
    end

    resources :properties do
      post :values
      delete '/values/:id' => 'properties#delete_value'
    end

    resources :feedbacks

    get '/categories/find/:id' => 'categories#find'

    get '/product/photos/:product_id' => 'photos#find'
    post '/product/photos/upload' => 'photos#upload'

    get '/category/photos/:category_id' => 'photos#find_category'
    post '/category/photos/upload' => 'photos#upload_category'

    get '/gallery/photos/:gallery_id' => 'photos#find_gallery'
    post '/gallery/photos/upload' => 'photos#upload_gallery'

    delete '/photos/:id' => 'photos#destroy'
    put '/photos/edit/:id' => 'photos#update'

    resources :galleries do

    end

  end

  post '/feedback/create' => 'feedbacks#create'

  root 'pages#index'

  get '/pages/carousel/:id' => 'pages#carousel'

  get '/product/filters/' => 'products#filters'

  get '/catalog/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/*section/:category_id/product/:product_id' => 'pages#product'

  get '/catalog' => 'pages#catalog'
  get '/catalog/:id' => 'pages#category'
  get '/catalog/*section/:id' => 'pages#category'
  get '/catalog/*section/*section/:id' => 'pages#category'

  get ':id' => 'pages#show'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :photos
  has_and_belongs_to_many :properties
  has_and_belongs_to_many :values


  # scope :filter, -> (value_id){ joins(:values).group("id"){ where(id: value_id)} }

  scope :filter, -> (value_id){ joins(:values).where('values.id = ?', value_id) }
  
  validates :price, :numericality => true


  # VALID_NAME_REGEX = /"Название продукта"/i
  validates :name, presence: true
  # validates :name, format: {with: VALID_NAME_REGEX}


  def prop_val
    @product_properties = []
    Property.all.each do |property|
      property_values = []
      property.values.each do |value|
        unless self.values.exists?(value)
          property_value = {id: value.id, value: value.value, checked: 0}
          property_values.push property_value
        else
          property_value = {id: value.id, value: value.value, checked: 1}
          property_values.push property_value
        end
      end
      product_property = {id: property.id, name: property.name, values: property_values}
      @product_properties.push product_property
    end
    return @product_properties
  end

  
  def update_all(params)
    unless params[:name] == "Название продукта"
      self.update(params)
      
      # {"1"=>{"ids"=>"1"}, "3"=>{"ids"=>false}, "4"=>{"ids"=>"4"}}
      if params[:product_categories]
        params[:product_categories].each do |item|
          @category = Category.find(item[0])
          unless self.categories.exists?(item[0])
            self.categories << @category
          end
          if item[1]['ids'] == false
            self.categories.delete(@category)
          end
        end
      end
    else
      self.destroy
    end
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :signed_in_manager, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :find, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  def index
    @products = Product.all
    @prod_delete = Product.find_by_name("Название продукта")
    if @prod_delete
      @prod_delete.destroy
    end
  end

  def show
  end

  def new
    @product = Product.new(:price => 0, :name => "Название продукта")
    if @product.save
      redirect_to edit_admin_product_url(@product)
    else
      render :json => {error: @product.errors}
    end
  end

  def edit
    @categories = Admin::Category.all
  end

  def find
    @categories = Admin::Category.all
    @properties_values = @product.prop_val
    render :json => {
        product: @product,
        product_categories: @product.categories,
        categories: @categories,
        properties: @properties_values
    }
  end


  def create
    @product = Product.new(product_params)
    if @product.save
      render :json => {success: @product}
    else
      render :json => {error: @product.errors}
    end
  end

  def update
    if @product.update_all(product_params)
      render :json => {success: @product}
    else
      render :json => {error: @product.errors}
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_property
    @product = Product.find(params[:product_id])
    @property = Property.find(params[:property_id])
    @product.properties << @property
    @properties = Property.all - @product.properties
    render :json => {
        properties: @properties,
        product_properties: @product.properties
    }
  end

  def set_property_value
    @product = Product.find(params[:product_id])
    @property = Property.find(params[:property_id])
    @value = Value.find(params[:value_id])
    unless @product.properties.exists?(@property)
      @product.properties << @property
    end
    unless @product.values.exists?(@value)
      @product.values << @value
    else
      @product.values.delete(@value)
      if @product.values.where(property_id: @value.property_id).length == 0
        @product.properties.delete(@property)
      end
    end
    render :json => {
        properties: @product.prop_val
    }
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    # params.require(:offer).permit!
    params.require(:product).permit(:name, :body, :price, :sale, :art, :property_id, :value_id, :product_categories => [:ids])
    # params.require(:user).permit( :attribute_translations => [:id => [:name, :city, :includes, :notes, :description, :slug]])
    # :attribute_translations => [:id => [:name, :city, :includes, :notes, :description, :slug]]
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def filters
    filters = []
    JSON.parse(params[:filters]).each do |f|
      filters.push f[1]
    end

    @products = Product.filter(filters.join(","))

    def prod_val(products, filters)
      @p = []
      if filters.length > 0
        f = filters.shift
        for product in products
          if product.values.exists?(f)
            @p.push product
          end
        end
        @p = @p.uniq
        prod_val(@p, filters)
      else
        return @p = products
      end
    end

    @products = prod_val(@products, filters)
    
    @res = []
    @products.each do |product|
      prod = {product: nil, values: nil}
      prod[:product] = product
      prod[:values] = product.values
      @res.push prod
    end

    render :json => @res
  end


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:price, :title, :body, :filters)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_categories.erb
<div class="form-group">
  <label>Категории товара</label>
  <%- @categories.each do |category| %>
      <div class="checkbox">
        <label>
          <%- if @product.categories.exists?(category.id) %>
              <input ng-checked="true" type="checkbox"
                     ng-model="obj.product.product_categories[<%= category.id %>].ids"
                     ng-true-value="<%= category.id %>">
          <%- else %>
              <input ng-checked="false" type="checkbox"
                     ng-model="obj.product.product_categories[<%= category.id %>].ids"
                     ng-true-value="<%= category.id %>">
          <% end %>
          <%= category.name %>
        </label>
      </div>
  <% end %>
</div>

app/views/admin/products/_form.slim
.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Информация о товаре

  .panel-body
    .alert.alert-danger ng-if="errors"
      ul ng-repeat="error in errors"
        li ng-bind="error"
    .row
      .col-md-8
        .form-group
          label for="name" Название
          input.form-control#name name="name" type="text" ng-model="obj.product.name"
      .col-md-4
        .form-group
          label for="price" Цена(руб.)
          input.form-control#price type="text" ng-model="obj.product.price"

    div
      label for="body_ru" Описание
      textarea.form-control#body_ru rows="4" ng-model="obj.product.body"


.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Фотографии товара
  .panel-body
    photos-uploaded resource-name="product" resource-id="#{@product.id}"
    uploader-component upload-url="/admin/product/photos/upload" resource-name="product_id" resource-id="#{@product.id}"


.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Категории товара
  .panel-body
    .row
      .col-sm-6
        =render 'admin/products/categories'

.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Свойства товара
  .panel-body
    .row
      .col-sm-6
        =render 'admin/products/properties'

app/views/admin/products/_properties.erb
<div class="row">
  <div class="col-sm-12">
    <h4><strong>Свойства товара</strong></h4>
    <div ng-repeat="property in properties" class="property">
      <h4>
        <span ng-bind="property.name"></span>
        <span class="btn btn-success btn-xs add-property"><span class="fa fa-plus"></span></span>
      </h4>
      <div class="row property_add" style="display: none">
        <div class="col-xs-8">
          <input type="text" class="form-control"
                 ng-model="property.name"
          >
        </div>
        <div class="col-xs-4">
          <span class="btn btn-success"
          ><span class="fa fa-plus"></span></span>
        </div>
      </div>
      <div class="checkbox" ng-repeat="value in property.values">
        <label>
          <input type="checkbox"
                 ng-model="property[$index]"
                 ng-change="setPropertyValue(obj.product.id, property.id, value.id)"
                 ng-checked="value.checked"
          >
          <span ng-bind="value.value"></span>
        </label>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/edit.slim
form ng-init="obj.authenticity_token = '#{form_authenticity_token}'" ng-controller="ProductsFormCtrl"
  .page-header
    h2 Редактирование товара
    .page-header-actions
      -if @product.created_at.nil?
        button.btn.btn-success type="submit" ng-click="submit()"
          i class="fa fa-floppy-o"
          | Сохранить
      -else
        button.btn.btn-success type="submit" ng-click="update(#{@product.id})" ng-init="findProduct(#{@product.id})"
          i class="fa fa-floppy-o"
          | Сохранить
      | &nbsp;
      =link_to "Отменить", admin_products_path, :class => "btn btn-default"
      /= link_to new_admin_product_path, class: 'btn btn-success' do
      /  i class="fa fa-plus"
      /  ' Добавить товар
      /
  =render 'admin/products/form'

app/views/admin/products/index.slim
.page-header
  h2 Список товаров
  .page-header-actions
    = link_to new_admin_product_path, class: 'btn btn-success' do
      i class="fa fa-plus"
      ' Добавить товар

.content
  table class="table table-bordered"
    thead
      tr
        th id
        th Название
        th Описание
        th Цена (руб.)
        th Фото
        th Свойства
        th Категория
        th Действия
  
    tbody
      -@products.each do |item|
        tr
          td=item.id
          td=item.name
          td=item.body
          td=item.price
          td
            .row
            -item.photos.each do |photo|
              .col-sm-6
                .thumbnail
                  =image_tag photo.photo.thumb
          td
            -item.properties.each do |property|
              dl
                dt=property.name
                -item.values.each do |value|
                  -if property.values.exists?(value)
                    dd=value.value
          td
            ul
              -item.categories.each do |category|
                li=category.name
          td
            = link_to edit_admin_product_path(item), class: 'btn btn-success' do
              span.fa.fa-lg.fa-edit
            br
            br
            = link_to admin_product_path(item), class: 'btn btn-danger', method: "delete" do
              span.fa.fa-lg.fa-trash
              
              
              